-- Fenéla local development seed data.
--
-- Intentionally empty: schema and RLS require no seed data.
-- Add synthetic fixtures only for a concrete need (e.g. RLS
-- ownership tests run via `supabase test db`).
