-- Fenéla service_role grant for privileged Device
-- enumeration during account deletion.
--
-- BYPASSRLS lets service_role skip Row Level Security policy evaluation,
-- but standard SQL GRANT/REVOKE table privileges are still enforced for
-- every role, service_role included. supabase/migrations/
-- 20260809120000_mvp2_persistence_foundation.sql only granted `devices`
-- privileges to `authenticated`.
--
-- The account deletion core (src/server/devices/listDeviceIdsForUser.ts)
-- must enumerate every Device a user owns before deleting their auth.users
-- row. It uses the privileged admin client deliberately (not the normal
-- RLS-scoped client) so the same trusted deletion core can later be reused
-- by inactivity deletion, which has no browser session or cookies to scope
-- a normal client.
--
-- Scoped to exactly SELECT on `devices` — the one read this enumeration
-- step performs. Not INSERT/UPDATE/DELETE: device creation/touch stays on
-- the normal authenticated RLS-scoped path (getOrCreateOwnDevice), and
-- Device rows are deleted only via the auth.users cascade, never directly.

grant select on public.devices to service_role;
