-- Fenéla service_role grants for the privileged
-- reflections write path.
--
-- As with push_subscriptions, the persistence foundation's
-- comment on `reflections` RLS explicitly anticipates that "Writes are
-- therefore expected to happen through trusted server-side application
-- code using the service_role key." BYPASSRLS lets service_role skip
-- Row Level Security policy evaluation; it does not grant standard SQL
-- table privileges, which Postgres still enforces for every role.
--
-- createReflectionForPeriod.ts inserts with .select().single() to return
-- the created row, so service_role needs both INSERT and SELECT.
--
-- Scoped to exactly what that one write boundary needs: INSERT (to create
-- a Reflection) and SELECT (PostgREST requires it to return the inserted
-- row's representation). No UPDATE/DELETE — reflections are immutable
-- historical artifacts (ADR-005); the existing `authenticated` grant
-- already covers all read access reflections needs elsewhere. Not
-- extended to any other table.

grant select, insert on public.reflections to service_role;
